// Generated by scripts/embed-marketplace-identity.mjs during image builds.
// Runtime environment variables cannot change these compile-time values.
export const GENERATED_DISTRIBUTION = "development";
export const GENERATED_MARKETPLACE_IDENTITY = {
  productCode: "",
  productSku: "",
  contractDimension: "",
  keyFingerprint: "",
} as const;
